version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
    environment:
      FLASK_DEBUG: 1
      UPLOAD_FOLDER: /app/uploads
      LOG_FOLDER: /app/logs
      STATIC_FOLDER: /app/staticfiles
    command: ["gunicorn", "app:app", "--bind", "0.0.0.0:8000", "--workers", "3"]
